### PR TITLE
autoFormat: disable T/F --> TRUE/FALSE transformation by default

### PR DESCRIPTION
**Pull request by mikapfl**
Hi,

today at the linter hackathon we noticed that the transformation within autoFormat which converts T and F into TRUE and FALSE after asking about it is not suited for the default `autoFormat` use case:
1. It has a lot of false positives, e.g. [(F) in comments](https://github.com/pik-piam/mrcommons/blob/master/R/toolPregnant.R#L8) and [F in strings](https://github.com/pik-piam/mrcommons/blob/master/R/toolPregnant.R#L15).
2. It asks *every single time* that `autoFormat` is executed, which makes false positives very annoying.
3. It doesn't fit with the overall very defensive defaults of `autoFormat` because a false positive which is answered "yes" will actually change the *meaning* of code.
4. It breaks non-interactive use, e.g. autoFormatting a whole package.

Therefore, it should be optional, and by default it should not be used. I still see its use when formatting an old function which uses T/F a lot, but it should not be the default.

Cheers,

Mika

### CODE REVIEW

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Hold my beverage …

**Review by pfuehrlich-pik — APPROVED** [review]
Agreed, it makes more sense this way. I'd also export `askFormatTF` so it can be run independently. I'd probably also remove the argument from autoFormat, so they are completely independent. We could point to `askFormatTF` and `snakeToCamel` in the documentation for autoFormat as interactive tools to deal with specific linter warnings.

**Comment by mikapfl** [comment]
> I'd also export askFormatTF so it can be run independently. I'd probably also remove the argument from autoFormat, so they are completely independent.

Done

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Counter offer: #144

**Comment by mikapfl** [comment]
I like the counter offer better.

**Pull request closed without merging**
