### PR TITLE
Revert "Improve logo with multi-line title in README"

### PR DESCRIPTION
**Pull request by jnnsbrr**
Reverts pik-piam/lucode2#209

### CODE REVIEW

**Comment by tscheypidi** [comment]
@jnnsbrr what is the issue with the last PR?

**Review by robinhasse — APPROVED** [review]
Sorry for that. I can create a PR to fix this soon but you can also revert it.

**Comment by robinhasse** [comment]
This problem caused by this PR should be fixed by #211. Do you still prefer the revert @tscheypidi or should we simply merge the fix?

**Comment by tscheypidi** [comment]
I'm in favor of just merging the fix in #211 after @jnnsbrr has reviewed it

**Pull request closed without merging**
